RESULTS_DIR: results
RUN_NAME: miyashita_all_logistic
AUTO_INCREMENT: true

grid_size: 30
noise_std: 0.5
num_uavs: 3
num_ugvs: 2
steps: 600

ugv_depth: 8
reward_type: 6
discount_factor: 0.95

gp_sensing_noise_sigma0: 0.4
gp_max_basis: 150
gp_threshold_delta: 0.05
rbf_sigma: 2.0

cfg.use_cbf: true
cfg.waypoint_mode: miyashita
# cfg.waypoint_mode: suenaga_dp
#cfg.waypoint_mode: ugv_future_point
# cfg.waypoint_mode: common_weighted

#cfg.nominal_mode: to_waypoint
#cfg.nominal_mode: to_ugv_future
#cfg.nominal_mode: to_ugv_future_if_in_voronoi_else_waypoint
cfg.nominal_mode: to_ugv_reachable_best_amb


cfg.use_voronoi: true

cfg.use_common_map: false
cfg.common_map_mode: direction
# cfg.common_map_mode:point
cfg.ugv_weight_eta: 0.3

cfg.d0: 5.0
cfg.ugv_future_path_sigma: 5.0
cfg.step_of_ugv_path_used: 6

cfg.ring_d_star: 8.0
cfg.ring_sigma: 4.0
cfg.use_ring: false


cfg.suenaga_rho: 0.95
cfg.suenaga_depth: 5

cfg.k_pp: 2.0
cfg.k_ugv: 2.0
cfg.v_limit: 5.0
cfg.control_period: 0.1

cfg.cbf_j_alpha: 1.0
cfg.cbf_j_gamma: 3.0

cfg.signal_mode: gp_logistic_prob
#cfg.signal_mode: gp_mean

#cfg.uav_waypoint_signal: gp_var
cfg.uav_waypoint_signal: prob_ambiguity

cfg.map_publish_period: 0.5

cfg.dir_num_steps: 8
cfg.dir_ell_u: 6.0
cfg.dir_ell_perp: 3.0
cfg.dir_eta_forward: 2.0
cfg.dir_forward_shift: 0.0
cfg.dir_mode: sum
cfg.dir_normalize: true

cfg.wp_use_topk_centroid: false
cfg.wp_topk: 60
cfg.wp_min_dist: 2.0
cfg.wp_power: 1.0

cfg.ugv_move_period: 5